  FILE DRIVER = F541D663-4A48-40AA-AABF-FF158CCAE34C {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/SmemDxe/SmemDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/SmemDxe/SmemDxe.efi
    SECTION UI = "SmemDxe"
  }
  FILE DRIVER = 2E3042F3-2BB9-463F-8866-56D75B7C4AB0 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/ChargerExDxe/ChargerExDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/ChargerExDxe/ChargerExDxe.efi
    SECTION UI = "ChargerExDxe"
  }
  
  FILE DRIVER = 11FAED4C-B21F-4D88-8E48-C4C28A1E50DF {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/UsbPwrCtrlDxe/UsbPwrCtrlDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/UsbPwrCtrlDxe/UsbPwrCtrlDxe.efi
    SECTION UI = "UsbPwrCtrlDxe"
  }
  FILE DRIVER = 5AF77F10-90DF-4E7E-8325-A17EC09D5443 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/UsbMsdDxe/UsbMsdDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/UsbMsdDxe/UsbMsdDxe.efi
    SECTION UI = "UsbMsdDxe"
  }
  
  FILE DRIVER = 94F8A6A7-DC34-4101-88C1-99179CCEAE83 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/UsbfnDwc3Dxe/UsbfnDwc3Dxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/UsbfnDwc3Dxe/UsbfnDwc3Dxe.efi
    SECTION UI = "UsbfnDwc3Dxe"
  }
  FILE DRIVER = 3ADF8DDA-1850-44C5-8C63-BB991849BC6F {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/HashDxe/HashDxe.efi
    SECTION UI = "HashDxe"
  }
  FILE DRIVER = CD823A4D-7DEC-4531-AE5D-4134FA4127B8 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/UsbConfigDxe/UsbConfigDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/UsbConfigDxe/UsbConfigDxe.efi
    SECTION UI = "UsbConfigDxe"
  }
  FILE DRIVER = 3299A266-15F0-4346-8318-716336736D3E {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/UsbDeviceDxe/UsbDeviceDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/UsbDeviceDxe/UsbDeviceDxe.efi
    SECTION UI = "UsbDeviceDxe"
  }
  FILE DRIVER = F09AD92E-485C-9CDB-3E05-3385C38F94CC {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/TsensDxe/TsensDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/TsensDxe/TsensDxe.efi
    SECTION UI = "TsensDxe"
  }
  FILE DRIVER = 569EA0DE-B557-4043-84CF-01103FE516E5 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/GpiDxe/GpiDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/GpiDxe/GpiDxe.efi
    SECTION UI = "GpiDxe"
  }
  FILE DRIVER = 5F0937CD-73F9-445E-B320-BB6FD5D3CBDE {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/CipherDxe/CipherDxe.efi
    SECTION UI = "CipherDxe"
  }
  FILE DRIVER = 32C71E68-83A8-46ED-AED1-094E71B12057 {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/SecRSADxe/SecRSADxe.efi
    SECTION UI = "SecRSADxe"
  }
  FILE DRIVER = 8BD3B475-401A-4B0B-9315-EDEE61A1EAE5 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/VcsDxe/VcsDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/VcsDxe/VcsDxe.efi
    SECTION UI = "VcsDxe"
  }
  
  FILE DRIVER = 53D39438-814A-4D9C-87C1-07E8C713F4C4 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/QcomMpmTimerDxe/QcomMpmTimerDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/QcomMpmTimerDxe/QcomMpmTimerDxe.efi
    SECTION UI = "QcomMpmTimerDxe"
  }
  FILE DRIVER = 068AAE46-BDC6-4073-85D5-31C5EEF19A15 {
    SECTION DXE_DEPEX = Platform/EFI_Binaries/Drivers/sm6375/MiTokenDxe/MiTokenDxe.depex
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/MiTokenDxe/MiTokenDxe.efi
    SECTION UI = "MiTokenDxe"
  }
  FILE DRIVER = C2F9A4F5-F7B4-43E7-BA99-5EA804CC103A {
    SECTION PE32 = Platform/EFI_Binaries/Drivers/sm6375/ASN1X509Dxe/ASN1X509Dxe.efi
    SECTION UI = "ASN1X509Dxe"
  }
  
  
  


  